export type LessonId = 'rhythm' | 'blob' | 'alternate' | 'stack' | 'movement' | 'gauntlet';
export type Prayer = 'magic' | 'range' | 'off';
export type Mode = 'guided' | 'challenge';
export interface Lesson { id: LessonId; title: string; tag: string; description: string; icon: string; level: string; objective: string; steps: string[]; takeaway: string; }
export const lessons: Lesson[] = [
  { id: 'rhythm', title: 'Find your rhythm', tag: 'THE FOUNDATIONS', description: 'Get comfortable with the beat of a game tick.', icon: 'protect-magic', level: 'Foundation', objective: 'Protect against a mager every fourth tick. Turn prayer off between attacks.', steps: ['A game tick lasts 0.6 seconds. This drill starts with an attack on tick 1, then 5, 9, and so on.', 'Select Magic before an attack tick. Select Off for the three quiet ticks that follow.', 'Follow the tick bar. Your prayer is checked when the bar fills.'], takeaway: 'This is lazy-flick timing practice. It scores active and idle ticks, not actual prayer-point drain.' },
  { id: 'blob', title: 'Read the blob', tag: 'KNOW YOUR ENEMY', description: 'Understand the scan. Make the right switch.', icon: 'blob', level: 'Foundation', objective: 'Let the blob read one protection prayer, then switch before its attack three ticks later.', steps: ['Begin on Magic or Ranged. The blob reads your prayer on tick 1, then every six ticks.', 'It chooses the opposite style. If it reads Magic, its attack will be Ranged on tick 4.', 'Switch after the read and before the attack. Holding that prayer until the next read is fine.'], takeaway: 'A blob is predictable when you control what it reads. The drill keeps it at a distance, so melee is excluded.' },
  { id: 'alternate', title: 'One tick at a time', tag: 'BUILD MUSCLE MEMORY', description: 'Make alternating prayers feel second nature.', icon: 'protect-range', level: 'Developing', objective: 'Alternate Magic and Ranged on every tick, starting with Magic.', steps: ['Prepare Magic for tick 1, Ranged for tick 2, then repeat.', 'The three-tick gap between a blob’s read and attack means it sees the opposite prayer at impact.', 'Keep the rhythm steady. This drill scores every tick of the pattern, even when no attack occurs.'], takeaway: 'Alternating protection prayers is different from double-clicking one prayer to conserve prayer points.' },
  { id: 'stack', title: 'Handle the stack', tag: 'TWO THREATS. ONE PLAN.', description: 'Keep a mager and ranger on separate beats.', icon: 'mager', level: 'Developing', objective: 'Protect Magic on ticks 1, 5, 9… and Ranged on ticks 3, 7, 11…', steps: ['These enemies are already offset by two ticks. Each attacks every four ticks.', 'Begin with Magic. Switch to Ranged after the magic attack, then back after the ranged attack.', 'Quiet ticks give you room to act. Only the attack ticks count towards your score.'], takeaway: 'This setup is deliberately offset. Two enemies attacking on the same tick need a positioning solve in the LoS tool.' },
  { id: 'movement', title: 'Switch & step', tag: 'FREE UP YOUR CLICKS', description: 'Keep your prayer while finding the next tile.', icon: 'player', level: 'Advanced', objective: 'Protect against alternating attacks and reach the marked tile every four ticks.', steps: ['Magic attacks on tick 1; Ranged on tick 3. The pattern repeats every four ticks.', 'Click the marked tile before tick 4, then follow the next target before tick 8.', 'Arrow keys also move one tile. Prayer keys are 1 for Magic, 2 for Ranged, and 0 for Off.'], takeaway: 'Marked tiles are a coordination exercise, not an Inferno floor attack. Click movement is simplified; there is no pathfinding.' },
  { id: 'gauntlet', title: 'Put it all together', tag: 'YOUR FINAL CHECKPOINT', description: 'A blob, a mager, and a reason to keep moving.', icon: 'ranger', level: 'Advanced', objective: 'Combine blob reads, four-tick magic attacks, and a movement target every four ticks.', steps: ['Start on Magic and alternate every tick. The mager attacks on odd ticks 1, 5, 9…', 'The blob reads on tick 1 and attacks three ticks later. Staying in rhythm covers both enemies.', 'Reach each marked tile before the fourth tick without losing your prayer rhythm.'], takeaway: 'Take this rhythm into wave simulations next. This is a focused drill, not a full combat or Zuk simulator.' },
];
export const TOTAL_TICKS = 36;
export const PASS_SCORE = 90;
export const sourceLinks = {
  wiki: 'https://oldschool.runescape.wiki/w/Inferno/Strategies',
  gnomonkey: 'https://www.youtube.com/watch?v=6trKOSUr4EM',
  los: 'https://los.inferno.tips/',
};
